base_url = "http://localhost:1111"
title = "My Docs"
theme = "default"

[markdown]
highlight_code = true
insert_anchor_links = "left"

[extra]
copyright_html = '<a href="/">My Docs</a> by Author via <a href="https://zorto.dev" target="_blank" rel="noopener">Zorto</a>'
