name: Release Python

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v0.1.0)"
        required: true

permissions:
  contents: read

jobs:
  release:
    uses: dkdc-io/.github/.github/workflows/release-python.yml@v1
    permissions:
      contents: read
      id-token: write
