name: Release GitHub

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v0.1.0)"
        required: true

jobs:
  release:
    uses: dkdc-io/.github/.github/workflows/release-github.yml@v1
    with:
      binary: zorto
    permissions:
      contents: write
